plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
# Site Settings
locale                   : "en-US"
title                    : "Will clients subscript a term deposit?"
title_separator          : "-"
subtitle                 : "Predict if the client will subscribe a term deposit or not, using Machine learning"
name                     : "lwy"
description              : "Predict if the client will subscribe a term deposit or not, using Machine learning"
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
head:
  teaser                   : screenshot.png
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
email: liuqun1006@gmail.com

