theme: jekyll-theme-cayman
title: Will clients subscript a term deposit?
email: liuqun1006@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
Can you imagine how difficult it is to start a business from new customers compared to old customers? 
The company spends a lot of manpower and financial resources to attract new customers, 
but the company is still not sure whether customers will show confidence in them. 
Therefore, why not try to make a new start with old customer? 
But how do we know whether they would buy subscript a term deposit here?
